[package]
name = "myluckysol"
version = "0.1.0"
description = "MyLuckySol - Provably Fair Solana Chance Game"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "myluckysol"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.0"
solana-program = "=1.18.0"
